# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Amazon"
  pre = "amazon"
  url = "https://www.amazon.co.uk/stores/author/B0CD5N8S5Q"
  weight = 20
[[main]]
  name = "Goodreads"
  pre = "goodreads"
  url = "https://www.goodreads.com/author/show/978806.Don_Morris"
  weight = 21

#[[main]]
#  name = "Blog"
#  pageRef = "posts"
#  weight = 10

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
[[footer]]
identifier = "amazon"
pre = "amazon"
url = "https://www.amazon.co.uk/stores/author/B0CD5N8S5Q"
weight = 20
[[footer]]
  identifier = "goodreads"
  pre = "goodreads"
  url = "https://www.goodreads.com/author/show/978806.Don_Morris"
  weight = 21
  [[footer]]
  identifier = "threads"
  pre = "threads"
  url = "https://www.threads.com/@donmorrisbooks"
  weight = 22
  [[footer]]
  identifier = "facebook"
  pre = "facebook"
  url = "https://www.facebook.com/profile.php?id=100093813489840"
  weight = 23
  [[footer]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://www.instagram.com/donmorrisbooks/"
  weight = 24
  [[footer]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://x.com/DonMorrisBooks"
  weight = 25
